services:

  api-connections:
    restart: always
    build:
      context: ./app_connect
      dockerfile: Dockerfile
    volumes:
      - ./app_connect:/app
    ports:
      - "5005:5005"
    env_file:
      - .env
    networks:
      - app_connect

networks:
  app_connect:
